### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by Prologs** [richardW8k/RWListFieldCalculations#7]
Hello,

I have an issue with calculations when I use the plugin List Field Number Format for Gravity Forms.
The total sum of columns of a list field is wrong, it seems to be a problem with float format and french notation (9.999,99), as @ovann86 says to me. 

Thank you for your help.

**Comment by ovann86** [comment]
Here's a change I did up to provide "decimal_comma" format support.

@Prologs  did you want to test it to confirm it works?

https://github.com/ovann86/RWListFieldCalculations/blob/master/js/LFCalc.js

The only issue I can see is if the column field contains the format that is opposite from the global format - because the earlier used gformToNumber() assumes the number you are converting is in the global format (which may not be the same as the fields format). Highly unlikely this will ever actually happen - I can't think of a legitimate reason for someone to design a form that asks for two different number formats.

**Comment by Prologs** [comment]
All my fields are at the same format (9.999,99), and the same rounded value (2 decimal with fixed point notation).
Everything works fine with integer numbers but when we have 2 decimal, the "Total" field is multiplied by 100 or 10000...
The problem is the same (sometimes) when I delete a line, the recalculation can be wrong.

**Comment by ovann86** [comment]
@Prologs did you get to try the updated LFCalc.js ? Did it add the "decimal_comma" format support for you?

**Comment by michaeledi** [comment]
@ovann86 Hi Ovann, could you check my submitted issue about this plugin? Thanks!

**Comment by ovann86** [comment]
@michaeledi  - it's still working for me in 2.1.3.
I have a list field, add a number field, click calculation and I see the list field as options.
Can you try on another clean WP install - maybe there's a conflict somewhere with another plugin or custom code?
This is what I see: https://demo.itsupportguides.com/asdf123.png
